language: python
python:
  - "3.6"

install:    
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install codeclimate-test-reporter

before_script:
  - psql -c 'create database test;' -U postgres

script:    
  - pytest --cov=app/api
  - coveralls

after_success:
  - coveralls
  - codeclimate-test-reporter