language: python
python:
  - "3.6"

services:
  - postgresql

addons:
  postgresql: "10.6"

postgres:
  adapter: postgresql
  database: myapp_test
  username: postgres

script:    
  - pytest --cov=app/api
  - coveralls

after_success:
  - coveralls
  - codeclimate-test-reporter

install:    
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install codeclimate-test-reporter